##
## EPITECH PROJECT, 2024
## myteams
## File description:
## Let's make a Teams!
##

MYTEAMS_HEXAGON_LIBRARY_DIR 	:= $(MYTEAMS_LIBRARY_DIR)/hexagon

MYTEAMS_HEXAGON_SRC_DIR			:= $(MYTEAMS_HEXAGON_LIBRARY_DIR)/src
MYTEAMS_HEXAGON_INC_DIR			:= $(MYTEAMS_HEXAGON_LIBRARY_DIR)/include

MYTEAMS_HEXAGON					:= $(MYTEAMS_HEXAGON_LIBRARY_DIR)/libhexagon.a
MYTEAMS_HEXAGON_SRC				:= \
	$(shell find $(MYTEAMS_HEXAGON_SRC_DIR) -type f -name '*.c')
MYTEAMS_HEXAGON_OBJ				:= $(MYTEAMS_HEXAGON_SRC:.c=.o)

export MYTEAMS_TARGETS      	+= $(MYTEAMS_HEXAGON)
export MYTEAMS_OBJ          	+= $(MYTEAMS_HEXAGON_OBJ)

MYTEAMS_HEXAGON_LOCAL_CFLAGS	:= $(CFLAGS) -fPIC
MYTEAMS_HEXAGON_LOCAL_CPPFLAGS	:= $(CPPFLAGS) -I$(MYTEAMS_HEXAGON_INC_DIR)

export CPPFLAGS					+= -I$(MYTEAMS_HEXAGON_INC_DIR)
export LDFLAGS 					+= \
	-L$(MYTEAMS_LIBRARY_DIR)/hexagon -lhexagon
#export LDFLAGS					+= \
#	-L$(MYTEAMS_LIBRARY_DIR)/hexagon -lhexagon \
#	-Wl,-rpath=$(MYTEAMS_LIBRARY_DIR)/hexagon

$(MYTEAMS_HEXAGON): CFLAGS=$(MYTEAMS_HEXAGON_LOCAL_CFLAGS)
$(MYTEAMS_HEXAGON): CPPFLAGS=$(MYTEAMS_HEXAGON_LOCAL_CPPFLAGS)
$(MYTEAMS_HEXAGON): $(MYTEAMS_HEXAGON_OBJ)
	$(AR) rcs $@ $^
